Mission05_pdg13/Models/GradeCalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission05_pdg13.Models
{
    public class GradeCalcModel
    {
        [Range(0, 100)]
        public string Assignments { get; set; }
        [Range(0, 100)]
        public string Project { get; set; }
        [Range(0, 100)]
        public string Quizzes { get; set; }
        [Range(0, 100)]
        public string MidExam { get; set; }
        [Range(0, 100)]
        public string FinalExam { get; set; }
        [Range(0, 100)]
        public string Intex { get; set; }
    }
}

Mission05_pdg13/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using Mission05_pdg13.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission05_pdg13.Controllers
{
    public class BlahController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalc()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalc(GradeCalcModel model)
        {
            return View();
        }
    }
}

Mission05_pdg13/Views/Blah/GradeCalc.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
}

@model Mission05_pdg13.Models.GradeCalcModel;

<!-- Grade Calculator form -->
<h3>Grade Calculator:</h3>
<div class="pg-text-centered">
    <form method="post">
        <div class="row">
            <div class="column">
                <label>Assignnments:</label>
                <input id="txtAssignments" asp-for="Assignments" /><br />
                <label>Group Project:</label>
                <input id="txtProject" asp-for="Project" /><br />
                <label>Quizzes:</label>
                <input id="txtQuizzes" asp-for="Quizzes" /><br />
                <label>Midterm Exam:</label>
                <input id="txtMidExam" asp-for="MidExam" /><br />
                <label>Final Exam:</label>
                <input id="txtFinalExam" asp-for="FinalExam" /><br />
                <label>Intex:</label>
                <input id="txtIntex" asp-for="Intex" /><br /><br />
            </div>
            <div class="column">
                <br /><br />
                <h5>Final Grade Percentage:</h5>
                <p id="GradePercent"></p>
                <br /><br />
                <h5>Final Letter Grade:</h5>
                <p id="GradeLetter"></p>
            </div>
        </div>
        <input id="btnSend" type="submit" value="Calculate Final Grade" />
        <div asp-validation-summary="All"></div>
    </form>
</div>

Mission05_pdg13/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Parker's Website";
}

<!-- Body Paragraph -->
<p>
    I'm excited to learn ASP.Net in IS 413! It will be my first strongly typed language which I think adds one of the finishing touches I'm looking for to complete my resume.
    During this semester I hope to learn more about the intricacies of web development. I have started a web development business and feel like more training could be critical
    to this venture's success.
</p>
<!-- Image of me doing something fun -->
<img src="img/pg.JPG" />
<h3>Top #3 Dream Jobs After Graduation:</h3>
<ol>
    <li>Solutions Architect</li>
    <li>Software Engineer</li>
    <li>Database Manager</li>
</ol>

Mission05_pdg13/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <!-- Add favicon to website -->
    <link rel="icon" type="image/x-icon" href="img/pg4.png" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="~/css/default.css" rel="stylesheet" />
</head>
<body>
    <!-- Bootstrap css navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark" id="mainNav">
        <div class="pg-nav">
            <div class="container">
                <div class="column">
                    <a asp-controller="Blah" asp-action="Index" class="navbar-brand"><h2>Parker George</h2></a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <!-- Nav bar to take to grade calculator -->
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a asp-controller="Blah" asp-action="GradeCalc" class="nav-link">Grade Calculator</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <div class="pg-body">
        @RenderBody()
    </div>

    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
    <script src="~/js/Grade.js"></script>

</body>
</html>